# Generated by Django 4.0.5 on 2022-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_passengers_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
