# Generated by Django 4.0.5 on 2022-09-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'db_table': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airlines')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'db_table': 'flights',
            },
        ),
    ]
