# Generated by Django 4.0.5 on 2022-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
