# Generated by Django 4.0.5 on 2022-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flights_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlines',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airlines',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airlines',
            name='head_quaters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airlines',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airlines',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
