# Generated by Django 4.0.5 on 2022-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airlines_country_airlines_established_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlines',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
