# Generated by Django 4.0.5 on 2022-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airlines_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='flight_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
